name: pythontests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.11', '3.12']  # Versión de Python a probar

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Si tienes un archivo de requisitos, instálalo aquí
        # pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest tests.test  # Ejecuta las pruebas en tests/test.py
